name: "Validate"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    name: "HACS Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@main"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        env:
          REPOSITORY_REF: "main"
        with:
          category: "integration"
          # Remove ignores as you complete repo metadata + brands setup.
          ignore: "brands topics description"

  validate-hassfest:
    name: "HASSFest Validation"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@main"

      - name: "Run HASSFest validation"
        uses: home-assistant/actions/hassfest@master
